package org.andrekreou.client;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.MediaType;
import org.andrekreou.mapper.StripeApiExceptionMapper;
import org.andrekreou.response.BalanceResponse;
import org.andrekreou.response.BalanceTransaction;
import org.eclipse.microprofile.rest.client.annotation.ClientHeaderParam;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * REST client interface for interacting with Stripe services.
 * <p>
 * This interface defines methods to perform CRUD operations by communicating
 * with Stripe through RESTful API calls.
 * </p>
 * <p>
 * The base URL for the REST calls is configured using the {@code stripe} config key in the
 * {@code application.properties} file.
 * </p>
 * <p>
 * The available methods include:
 * <ul>
 *     <li>Retrieving balance transaction data</li>
 * </ul>
 * </p>
 * <p>
 * This interface is annotated with {@link RegisterRestClient} to indicate that it is a REST client
 * and the base URL is configured via the {@code stripe} configuration key. It is also annotated with
 * {@link ClientHeaderParam} to access the endpoint via a secret key generated by Stripe. Finally, the
 * {@link RegisterProvider} is used to handle the incoming errors from Stripe services.
 * </p>
 *
 * @see RegisterRestClient
 * @see RegisterProvider
 * @see ClientHeaderParam
 */
@RegisterRestClient(configKey = "stripe")
@RegisterProvider(StripeApiExceptionMapper.class)
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@ClientHeaderParam(name = "Authorization", value = "${stripe.sandbox.key}")
public interface StripeClient {

    /**
     * Retrieves a balance transaction that represent funds moving through Stripe account using
     * a transaction id.
     * <p>
     * This method sends a GET request to the {@code /balance_transactions/{id}} endpoint of Stripe
     * to fetch the details of a balance transaction.
     * </p>
     *
     * @param transactionId the id of the transaction to fetch
     * @return the {@link BalanceTransaction} object representing the balance transaction response
     */
    @GET
    @Path("/balance_transactions/{id}")
    BalanceTransaction retrieveBalanceTransaction(
            @PathParam("id") String transactionId
    );

    /**
     * Retrieves the balance transactions that represent funds moving through Stripe account.
     * <p>
     * This method sends a GET request to the {@code /balance_transactions} endpoint of Stripe
     * to fetch the details of balance transactions.
     * </p>
     *
     * @param limit the number of transactions to fetch
     * @return the {@link BalanceResponse} object representing the balance transactions response
     */
    @GET
    @Path("/balance_transactions")
    BalanceResponse retrieveBalanceTransactions(
            @QueryParam("limit") int limit
    );
}
